In [ ]:
# Define the preprocess function
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Downlaod resources
nltk.download("punkt")
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

# Define Preprocess function
def preprocess(text):
    # Lowercase
    text = text.lower()

    # tokennization
    words = word_tokenize(text)

    # remove stopwords
    filtered_words = [word for word in words if word not in stop_words]

    # connect the result
    return " ".join(filtered_words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\郭丁恺\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\郭丁恺\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
import pandas as pd
# The original dataset
df = pd.read_csv("Reuter_test.csv")
df.head(10)

,text,text_type,topics,lewis_split,cgis_split,old_id,new_id,places,people,orgs,exchanges,date,title
0,Mounting trade friction between the\nU.S. And ...,"""NORM""",['trade'],"""TEST""","""TRAINING-SET""","""3809""","""14826""",['hong-kong' 'usa' 'japan' 'taiwan' 'malaysia'...,[],[],[],8-APR-1987 01:03:47.52,ASIAN EXPORTERS FEAR DAMAGE FROM U.S.-JAPAN RIFT
1,A survey of 19 provinces and seven cities\nsho...,"""NORM""",['grain'],"""TEST""","""TRAINING-SET""","""3811""","""14828""",['china'],[],[],[],8-APR-1987 01:19:17.29,CHINA DAILY SAYS VERMIN EAT 7-12 PCT GRAIN STOCKS
2,The Ministry of International Trade and\nIndus...,"""NORM""",['crude' 'nat-gas'],"""TEST""","""TRAINING-SET""","""4356""","""14829""",['japan'],[],[],[],8-APR-1987 01:22:17.25,JAPAN TO REVISE LONG-TERM ENERGY DEMAND DOWNWARDS
3,Thailand's trade deficit widened to 4.5\nbilli...,"""NORM""",['trade' 'grain' 'rice' 'corn' 'sugar' 'tin' '...,"""TEST""","""TRAINING-SET""","""3815""","""14832""",['thailand'],[],[],[],8-APR-1987 01:45:09.09,THAI TRADE DEFICIT WIDENS IN FIRST QUARTER
4,Indonesia expects crude palm oil (CPO)\nprices...,"""NORM""",['veg-oil' 'palm-oil'],"""TEST""","""TRAINING-SET""","""3816""","""14833""",['indonesia' 'malaysia'],[],[],[],8-APR-1987 01:48:20.11,INDONESIA SEES CPO PRICE RISING SHARPLY
5,NaN,"""BRIEF""",[],"""TEST""","""TRAINING-SET""","""3818""","""14835""",[],[],[],[],8-APR-1987 02:11:57.43,Japan four-year note auction average yield rec...
6,"Tug crews in New South Wales (NSW),\nVictoria ...","""NORM""",['ship'],"""TEST""","""TRAINING-SET""","""3822""","""14839""",['australia'],[],[],[],8-APR-1987 02:42:14.86,AUSTRALIAN FOREIGN SHIP BAN ENDS BUT NSW PORTS...
7,The Indonesian Commodity Exchange is\nlikely t...,"""NORM""",['veg-oil' 'palm-oil' 'lumber' 'coffee' 'rubber'],"""TEST""","""TRAINING-SET""","""4358""","""14840""",['indonesia' 'south-korea' 'taiwan'],[],[],[],8-APR-1987 02:56:07.22,INDONESIAN COMMODITY EXCHANGE MAY EXPAND
8,Food Department officials said the U.S.\nDepar...,"""NORM""",['grain' 'wheat'],"""TEST""","""TRAINING-SET""","""3824""","""14841""",['sri-lanka' 'usa'],[],[],[],8-APR-1987 03:09:59.77,SRI LANKA GETS USDA APPROVAL FOR WHEAT PRICE
9,Western Mining Corp Holdings Ltd\n&lt;WMNG.S> ...,"""NORM""",['gold'],"""TEST""","""TRAINING-SET""","""3825""","""14842""",['australia'],[],[],[],8-APR-1987 03:21:39.74,WESTERN MINING TO OPEN NEW GOLD MINE IN AUSTRALIA

In [ ]:
# Save the preprocessed dataset
# Load the dataset with selected column
df = pd.read_csv("Reuter_test.csv", usecols=["title","text","old_id"])

# Rename the column to fit into the index
df.rename(columns = {"old_id": "docno"}, inplace = True)
new_order = ["docno", "title", "text"]
df = df[new_order]

# drop the data which its text or title is NaN
df = df.dropna(subset=["text","title"])

# Preprocess the text and title field
df['text'] = df['text'].apply(preprocess)
df['title'] = df['title'].apply(preprocess)

# Save cleaned dataset
df.to_csv("cleaned_dataset.csv")

,docno,title,text
0,"""3809""",asian exporters fear damage u.s.-japan rift,mounting trade friction u.s. japan raised fear...
1,"""3811""",china daily says vermin eat 7-12 pct grain stocks,survey 19 provinces seven cities showed vermin...
2,"""4356""",japan revise long-term energy demand downwards,ministry international trade industry ( miti )...
3,"""3815""",thai trade deficit widens first quarter,thailand 's trade deficit widened 4.5 billion ...
4,"""3816""",indonesia sees cpo price rising sharply,indonesia expects crude palm oil ( cpo ) price...
6,"""3822""",australian foreign ship ban ends nsw ports hit,"tug crews new south wales ( nsw ) , victoria w..."
7,"""4358""",indonesian commodity exchange may expand,indonesian commodity exchange likely start tra...
8,"""3824""",sri lanka gets usda approval wheat price,food department officials said u.s. department...
9,"""3825""",western mining open new gold mine australia,western mining corp holdings ltd & lt ; wmng.s...
10,"""3826""",sumitomo bank aims quick recovery merger,sumitomo bank ltd & lt ; sumi.t > certain lose...

In [ ]:
# Display first 10 data
df.head(10)